### PR TITLE
Update apiVersion for shell script example

### PR DESCRIPTION
**Pull request by joejulian**
**What this PR does / why we need it**:
Update apiVersion for shell script example
**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

### CODE REVIEW

**Review by tenstad — APPROVED** [review]

**Comment by tenstad** [comment]
Closes https://github.com/kudobuilder/kuttl.dev/issues/33

**Review by alenkacz — APPROVED** [review]

**Review by alenkacz — CHANGES_REQUESTED** [review]
@joejulian can you signoff, please? :) https://github.com/kudobuilder/kuttl.dev/pull/32/checks?check_run_id=2141120048

**Comment by joejulian** [comment]
I can, but your doc-edit workflow doesn't make this obvious for casual contributors. From the [documentation itself](https://kuttl.dev/docs/testing/steps.html), there's a link:
image
This takes you to a github edit page that you can contribute directly from. Once contributed from that page, there's no github way to edit that commit message.

I'm not sure what the improvement should be, but this doesn't make for a good contributor experience.

**Comment by alenkacz** [comment]
@joejulian yeah I know :( I also complained about it a while back. I don't really have a good solution for this though, do you have any suggestion?

**Review by alenkacz — APPROVED** [review]

**Pull request merged**
